#!/usr/bin/env bash
# A script that transfers a file from our client to a server:
# Requirements:
#  -> Accepts 4 parameters:
#  ->  => The path to the file to be transferred
#      => The IP of the server we want to transfer the file to
#      => The username scp connects with
#      => The path to the SSH private key that scp uses
#  -> Displays Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#     + if less than 3 parameters passed
#  -> scp transfers the file to the users home directory ~/
#  -> Strict host key checking must be disabled when using scp

if (("$#" < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi



if (("$#" >= 4)); then
    ssh_key="$(realpath $4)"
else
   ssh_key="$(realpath ~/.ssh/school)"
fi

vsource="$1"
vdest="~/iscaba"
vuser="$3"
vip="$2"

scp  -i "$ssh_key" -o "StrictHostKeyChecking=off" "$vsource" "$vuser"@"$vip":"$vdest"
