#!/usr/bin/env bash
# a script that configures an nginx server to return a string
# content of the string is 'hello world'

function install_nginx(){
    check_ufw="$(which ufw)"
    apt-update
    apt-get install nginx -y

    if [[ -z "$check_ufw" ]]; then
	apt-get install ufw -y
    fi
    ufw enable
    ufw allow 'Nginx HTTP'
}

function set_default_ip(){
    default_f="/etc/nginx/sites-available/default"
    ip6_reg="listen \[::\]:[0-9]*]* default_server;"
    ip6_rep="listen [::]:80 default_server;"
    ip4_reg="listen [0-9]* default_server;"
    ip4_rep="listen 80 default_server;"
    cat "$default_f" | sed -E "s/$ip6_reg/$ip6_rep/" > "default.temp"
    cat "default.temp" | sed -E "s/$ip4_reg/$ip4_rep/" > "$default_f"
    rm -f "default.temp"
}

check="$(which nginx)"

if [[ -z "$check" ]]; then
    install_nginx
    check="$(which nginx)"
    "$check"
fi

set_default_ip
echo "Hello World!" > "./index.html"
mv "./index.html" "/var/www/html/"
