#!/usr/bin/env bash
# configures a server with a custom header

config_file="/etc/nginx/sites-available/default"
apt update
apt install -y nginx

# write config to nginx config file
cat <<CONFIG | tee "$config_file" > /dev/null
    server {
    	   listen 80 default_server;
	   listen [::]:80 default_server;
	   server_name _;
	   root /var/www/html;
	   index index.html;

	   location / {
	   	try_files \$uri \$uri/ =404;
		add_header X-Served-By \$hostname;
	   }
    }
CONFIG
echo "Hello World!" > '/var/www/html/index.html'

# reboot nginx
systemctl reload nginx
systemctl start nginx
