#!/usr/bin/env bash
# configures a server with a custom header

check="$(which nginx)"
if [[ -z "$check" ]]; then
    echo 'y' | ./install_webserver
fi

cat > /etc/nginx/sites-available/default <<EOF
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       root /var/www/html;
       index index.html index.htm index.nginx-debian.html;

       server_name _;
       location / {
       		try_files \$uri \$uri/ =404;
		add_header X-Served-By \$hostname;
       }
}
EOF
systemctl restart nginx
