#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server.

apt update -y
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends software-properties-common
DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:vbernat/haproxy-2.9
DEBIAN_FRONTEND=noninteractive apt-get install -y haproxy=2.9.\*


cat <<EOF | tee -a "/etc/haproxy/haproxy.cfg" > /dev/null

frontend lb_frontend
         bind *:80
         mode http
         default_backend web_servers

backend web_servers
        balance roundrobin
        mode http
        server web_01 34.239.254.5:80 check
        server web_02 100.27.12.254:80 check
EOF

echo "ENABLED=1" | tee -a "/etc/default/haproxy" > /dev/null
systemctl restart haproxy
