#!/usr/bin/env bash
# a script that configures an nginx server to return a string
# content of the string is 'hello world'

function install_nginx(){
    check_ufw="$(which ufw)"
    apt update
    apt install nginx -y
    systemctl start nginx

    if [[ -z "$check_ufw" ]]; then
        apt install ufw -y
    fi
    ufw enable
    ufw allow 'Nginx HTTP'
}

function set_default_ip(){
    default_f="/etc/nginx/sites-available/default"
    ip6_reg="listen \[::\]:[0-9]*]* default_server;"
    ip4_reg="listen [0-9]* default_server;"
    ip6_rep="listen [::]:80 default_server;"
    ip4_rep="listen 80 default_server;"
    sed -Ei "s/$ip6_reg/$ip6_rep/" "$default_f"
    sed -Ei "s/$ip4_reg/$ip4_rep/" "$default_f"
}

check="$(which nginx)"

if [[ -z "$check" ]]; then
    install_nginx
    set_default_ip
fi
