#!/usr/bin/env bash
# bash script to backup all databases on a mysql server

# create dump and archive of all databases
2>/dev/null mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf "$(date +%d-%m-%Y).tar.gz" backup.sql
