#!/usr/bin/env bash
# a script that configures an nginx server to listen on port 80

server_config="
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		try_files \$uri \$uri/ =404;
	}

}
"
echo "$server_config" > /etc/nginx/sites-enabled/default
service nginx restart
