#!/usr/bin/env bash
### manages file 'manage_my_process'

start_process()
{
	./manage_my_process &
	echo "$!" > "/var/run/my_process.pid"
	echo "manage_my_process started"
}


stop_process()
{
	pid=$(head -1 < /var/run/my_process.pid)
	kill -KILL "$pid" 2>/dev/null
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}


restart_process()
{
	stop_process
	start_process
	echo "manage_my_process restarted"
}

case $1 in
	"start")
		start_process
		;;
	"stop")
		stop_process
		;;
	"restart")
		restart_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
