#!/usr/bin/env bash
### A script that writes:
# 'I am alive!' infinitely to '/tmp/my_process'
# sleeps for 2
###

file='/tmp/my_process'
if [ ! -f "$file" ]; then
	touch "$file"
	chmod o+w "$file"
fi

while true; do
	echo "I am alive!" >> "$file"
	sleep 2
done
