#!/usr/bin/env bash
# A bash script that creates a story from the /etc/passwd file
# For each entry in the file, it prints:
# ``The user USERNAME is part of the GROUP_ID gang, lives in
#	HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is
#	protected by the passcode PASSWORD, more info about the user
#	here: USER ID INFO``
# 0-user | 1-passwd | 2-uid | 3-gid | 4-detail | 5-home_dir
# 6-terminal

while read -r line; do
	IFS=':' read -ra temp <<< "$line"
	echo "The user ${temp[0]} is part of the ${temp[3]} gang, lives in ${temp[5]} and rides ${temp[6]}. ${temp[2]}'s place is protected by the passcode ${temp[1]}, more info about the user here: ${temp[4]}"
done < "/etc/passwd"
