#!/usr/bin/env bash
# displays 'Best School' 10 times. At 9th time, print 'Hi after.
# printing 'Best School'. Must use 'while' and 'if' statements

n=0
while (( n < 10 )); do
	if (( n == 9 )); then
		echo "Hi"
	fi
	echo "Best School"
	n=$((n + 1))
done
