#!/usr/bin/env bash
# A bas script that loops from 1 to 10 and:
#+  displays 'bad luck' for the 4th loop iteration
#+  displays 'good luck' for the 8th loop iteration
#+  displays 'Best School' for the other iterations
# Must use the while loop (for and until are forbidden)
# Must use the if, elif and else statements.

n=0
while (( n < 10 )); do
	if (( n == 3 )); then
		echo "bad luck"
	elif (( n == 7 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
