#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes:
#+  display hours from 0 to 12
#+  display minutes from 1 to 59
# Must use the while loop (for and until are forbidden)

hours=0
while (( hours <= 12 )); do
	echo "Hour $hours"
	mins=1
	while (( mins <= 59 )); do
		echo $mins
		mins=$((mins + 1))
	done
	hours=$((hours + 1))
done
