#!/usr/bin/env bash
# A Bash script that displays:
#+	The content of the current directory in a 'list' format
#+	Only the part of the name after the first dash is displayed
# Must use the for loop (while and until are forbidden)
# Hidden files should not be displayed

files=$(ls)
for file in $files; do
	echo "$file" | cut -d '-' -f2-
done
