#!/usr/bin/env bash
#configures nginx on ubuntu to listen on port 8080 as user nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u service nginx restart
