#!/usr/bin/env bash
# a script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu


key_f="$(realpath ~/.ssh/school)"
pub_key="$(ssh-keygen -y -f $key_f)"
ssh -i ".ubuntu_user" ubuntu@100.25.200.149 "echo $pub_key >> ~/.ssh/authorized_keys"
ssh -i "$key_f" ubuntu@100.25.200.149
